[package]
name = "tnexus-api"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tnexus-api"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
chrono = { workspace = true }
dotenvy = { workspace = true }
futures = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
image = { workspace = true }
base64 = { workspace = true }
uuid = { workspace = true }
tnexus-auth = { workspace = true }
tnexus-domain = { workspace = true }
tnexus-image-archive = { path = "../tnexus-image-archive" }
tnexus-storage = { workspace = true }
tnexus-accounts-db = { workspace = true }
