server {
    listen 10.3.0.7:80;
    server_name imagemanager.relai.asia;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://tnexus.relai.asia$request_uri;
    }
}

server {
    listen 10.3.0.7:443 ssl http2;
    server_name imagemanager.relai.asia;

    ssl_certificate /etc/letsencrypt/live/imagemanager.relai.asia/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/imagemanager.relai.asia/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;

    return 301 https://tnexus.relai.asia$request_uri;
}
