[package]
name = "tnexus-worker"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tnexus-worker"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
dotenvy = { workspace = true }
redis = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
tnexus-domain = { workspace = true }
tnexus-storage = { workspace = true }
